import PDFDocument from 'pdfkit';
import type { BandData } from './types.js';

/**
 * PDF Generator for Band Profiles
 */
export class PdfGenerator {
  /**
   * Generate PDF profile for a band
   */
  static async generateProfile(bandData: BandData): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: 'A4',
          margin: 50,
          info: {
            Title: `${bandData.bandName} - Band Profile`,
            Author: 'AetherWave Band Generator',
            Subject: 'Virtual Band Profile'
          }
        });

        const chunks: Buffer[] = [];
        doc.on('data', (chunk) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));
        doc.on('error', reject);

        // Header
        doc.fontSize(32)
           .fillColor('#1a1a2e')
           .text(bandData.bandName, { align: 'center' });

        doc.moveDown(0.5);

        // Genre badge
        doc.fontSize(14)
           .fillColor('#e94560')
           .text(bandData.genre.toUpperCase(), { align: 'center' });

        doc.moveDown(1);

        // Philosophy/Motto
        if (bandData.philosophy) {
          doc.fontSize(12)
             .fillColor('#666666')
             .font('Helvetica-Oblique')
             .text(`"${bandData.philosophy}"`, { align: 'center' });
          doc.font('Helvetica');
        }

        doc.moveDown(1.5);

        // Band Identity
        if (bandData.band_identity) {
          this.addSection(doc, 'BAND IDENTITY', bandData.band_identity);
        }

        // Motto
        if (bandData.band_motto) {
          this.addSection(doc, 'MOTTO', `"${bandData.band_motto}"`);
        }

        // Members
        if (bandData.members && bandData.members.length > 0) {
          doc.fontSize(14)
             .fillColor('#00ffff')
             .text('MEMBERS', { underline: true });
          doc.moveDown(0.5);

          bandData.members.forEach((member) => {
            doc.fontSize(12)
               .fillColor('#1a1a2e')
               .text(member.name, { continued: true })
               .fillColor('#666666')
               .text(` - ${member.role}`);

            if (member.archetype) {
              doc.fontSize(10)
                 .fillColor('#888888')
                 .text(`   ${member.archetype}`);
            }
            doc.moveDown(0.3);
          });

          doc.moveDown(0.5);
        }

        // Signature Sound
        if (bandData.signatureSound) {
          this.addSection(doc, 'SIGNATURE SOUND', bandData.signatureSound);
        }

        // Influences
        if (bandData.influences && bandData.influences.length > 0) {
          doc.fontSize(14)
             .fillColor('#00ffff')
             .text('INFLUENCES', { underline: true });
          doc.moveDown(0.3);
          doc.fontSize(11)
             .fillColor('#333333')
             .text(bandData.influences.join(' • '));
          doc.moveDown(1);
        }

        // Tags
        if (bandData.tags && bandData.tags.length > 0) {
          doc.fontSize(14)
             .fillColor('#00ffff')
             .text('TAGS', { underline: true });
          doc.moveDown(0.3);
          doc.fontSize(11)
             .fillColor('#333333')
             .text(bandData.tags.join(' | '));
          doc.moveDown(1);
        }

        // Origin Story
        if (bandData.world_building?.origin_story) {
          this.addSection(doc, 'ORIGIN STORY', bandData.world_building.origin_story);
        }

        // Band Concept
        if (bandData.bandConcept) {
          this.addSection(doc, 'BAND CONCEPT', bandData.bandConcept);
        }

        // Footer
        doc.moveDown(2);
        doc.fontSize(8)
           .fillColor('#aaaaaa')
           .text('Generated by AetherWave Band Generator', { align: 'center' });
        doc.text(`Song: ${bandData.songName || 'Unknown'}`, { align: 'center' });

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  /**
   * Add a section with title and content
   */
  private static addSection(doc: PDFKit.PDFDocument, title: string, content: string) {
    doc.fontSize(14)
       .fillColor('#00ffff')
       .text(title, { underline: true });
    doc.moveDown(0.3);
    doc.fontSize(11)
       .fillColor('#333333')
       .text(content);
    doc.moveDown(1);
  }
}
